# file: roles/openshift.prereq/tasks/rhel.yml
---

- name: Install base packages
  yum:
    name: "{{ rhel_base_pkgs }}"
    state: present
  async: 10800
  poll: 0
  register: rhel_base_pkg_status

- name: 'Check on base package install ...'
  async_status: jid={{ rhel_base_pkg_status.ansible_job_id }}
  register: job_result
  until: job_result.finished
  delay: 30
  retries: 720


- name: Update the system to the latest packages
  yum:
    name: "*"
    state: latest
  async: 10800
  poll: 0
  register: rhel_upgrade_status

- name: 'Check on latest package update ...'
  async_status: jid={{ rhel_upgrade_status.ansible_job_id }}
  register: job_result
  until: job_result.finished
  delay: 30
  retries: 720

- name: Install OpenShift packages
  yum:
    name: "{{ rhel_ose_pkgs }}"
    state: present
  async: 10800
  poll: 0
  register: install_rhocp_packages_status

- name: 'Check on rhocp packages install ...'
  async_status: jid={{ install_rhocp_packages_status.ansible_job_id }}
  register: job_result
  until: job_result.finished
  delay: 30
  retries: 720


#- name: Remove atomic-openshift packages in the host’s /etc/yum.conf file when installing
#  command: atomic-openshift-excluder unexclude

- name: Eanble insecure registry
  shell: sed -i '/OPTIONS=.*/c\OPTIONS="--selinux-enabled --insecure-registry 172.30.0.0/16 --log-opt max-size=1M --log-opt max-file=3"' /etc/sysconfig/docker

- name: Prepare additional block device
  shell: echo -e "WIPE_SIGNATURES=true\nDEVS={{ os_docker_block_device }}\nVG={{ os_docker_volume_group }}" >> /etc/sysconfig/docker-storage-setup

- name: Create 'docker-pool' logical volume
  command: docker-storage-setup

- name: Reboot the host
  reboot:

- name: Start docker
  service: name=docker state=started enabled=yes

- name: get EC2 Facts
  action: ec2_metadata_facts

- debug: var=hostvars

- name: Template inventory file to host
  template: dest={{ default_home }}/inventory_ose  src=inventory_ose.j2
