# file: roles/admin_server_config/tasks/main.yml
---

#---------------------------------------------------
# deliver configuration to admin server
#---------------------------------------------------
- name: install required packages
  package:
    name:
    - bash-completion
    - mosh
    - python3-pip
    - rsync
    - vim
    state: present
- name: install required Python packages
  pip:
    name:
    - ansible
    - boto
    - boto3
- name: create src directory
  file:
    path: "~/src"
    state: directory
  become: no
- name: sync content to admin host
  synchronize:
    src: "{{ item }}"
    dest: "~/src/"
    rsync_opts:
    - "--exclude=group_vars/all.yml"
    - "--exclude=group_vars/.all.yml.swp"
  with_items:
  - "{{ lookup('env','PWD') }}/../roles"
  - "{{ lookup('env','PWD') }}"
- name: template files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  become: no
  with_items:
  - { src: bashrc.j2, dest: ~/.bashrc, mode: '0755' }
  - { src: env.sh.j2, dest: "~/src/{{ playbook_dir | regex_replace('^.*\/','') }}/env.sh", mode: '0755' }
- name: copy credentials to admin host
  copy:
    src: "{{ deploy_working_dir }}/aws_credentials_vault.yml"
    dest: "~/src/{{ playbook_dir | regex_replace('^.*\/','') }}/aws_credentials_vault.yml"
    mode: '0644'
    decrypt: no
  become: no
- name: copy group_vars/all.yml to remote host
  copy:
    src: "{{ deploy_working_dir }}/all.yml"
    dest: "~/src/{{ playbook_dir | regex_replace('^.*\/','') }}/group_vars/all.yml"
    mode: '0644'
  become: no
